version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.13-alpine
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      # Install via apk on alpine based images
      - run:
          name: Install Docker client
          command: apk add docker-cli

      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t awscyberrange/circleci-demo-docker:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push awscyberrange/circleci-demo-docker:$TAG